#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"

bash "$repo_root/tests/foundation_scaffold_test.sh"
bash "$repo_root/tests/task_to_job_test.sh"
bash "$repo_root/tests/stream_classify_test.sh"
bash "$repo_root/tests/execute_job_test.sh"
bash "$repo_root/tests/advisory_mode_test.sh"
bash "$repo_root/tests/checkpoint_test.sh"
bash "$repo_root/tests/listener_dispatch_test.sh"
bash "$repo_root/tests/hook_lifecycle_test.sh"
bash "$repo_root/tests/queue_cli_test.sh"
bash "$repo_root/tests/queue_lifecycle_test.sh"
bash "$repo_root/tests/worker_reliability_test.sh"
bash "$repo_root/tests/concurrency_stress_test.sh"
bash "$repo_root/tests/runtime_hardening_test.sh"
bash "$repo_root/tests/scheduler_dashboard_test.sh"
bash "$repo_root/tests/orchestration_loop_test.sh"
bash "$repo_root/tests/orchestration_autonomy_test.sh"
bash "$repo_root/tests/contracts_validation_test.sh"
bash "$repo_root/tests/review_batch_test.sh"
bash "$repo_root/tests/review_batch_cli_test.sh"
bash "$repo_root/tests/docs_tracking_test.sh"
bash "$repo_root/tests/metrics_snapshot_test.sh"
bash "$repo_root/tests/wake_queue_test.sh"
bash "$repo_root/tests/task_claim_test.sh"
bash "$repo_root/tests/review_runtime_integration_test.sh"
bash "$repo_root/tests/reviewer_policy_runtime_test.sh"
bash "$repo_root/tests/openclaw_test.sh"
bash "$repo_root/tests/import_project_test.sh"
bash "$repo_root/tests/guardrails_test.sh"
bash "$repo_root/tests/trigger_contract_test.sh"
bash "$repo_root/tests/workflow_contract_test.sh"
bash "$repo_root/tests/command_registry_test.sh"
bash "$repo_root/tests/task_graph_lint_test.sh"
bash "$repo_root/tests/decision_log_test.sh"
bash "$repo_root/tests/workflow_graph_artifact_test.sh"
bash "$repo_root/tests/event_replay_test.sh"
bash "$repo_root/tests/decompose_epic_test.sh"
bash "$repo_root/tests/workflow_enforcement_test.sh"
bash "$repo_root/tests/epic_status_test.sh"
